name: ci

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  ci:
    name: ci
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: |
            sandbox = true
            sandbox-fallback = false

      - name: Nix version
        run: nix --version

      - name: Show Nix config
        run: nix config show

      - name: Xcode version
        run: /Applications/Xcode_16.1.0.app/Contents/Developer/usr/bin/xcodebuild -version

      # See ${workspace}/nix/overlays/xcode.md
      - name: Set up Xcode in Nix store
        run: |
          XCODE_APP=$(realpath /Applications/Xcode_16.1.0.app)
          NIX_STORE_PATH="/nix/store/v92p4w6nxhyhq6lv0maq5cbb59mbxw5b-Xcode.app"
          HASH="sha256:d63c91255c8e98603b7f1470067c5225ab673850eed35449f5a0105c936e581c"

          sudo cp -a $XCODE_APP $NIX_STORE_PATH
          sudo sqlite3 /nix/var/nix/db/db.sqlite "INSERT INTO ValidPaths (path,hash,registrationTime) VALUES ('$NIX_STORE_PATH','$HASH',$(date +%s))"

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION=${{ github.event.inputs.version }}
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=develop
          fi

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo ${VERSION}

      - name: Build
        run: |
          VERSION=${{ steps.version.outputs.version }}
          echo \"$VERSION\" > nix/utils/default/version.nix
          nix build -v

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          fail_on_unmatched_files: true
          files: |
            result/*.tar.gz
